#!/usr/bin/env bash

# Render server configs and the three client subscriptions from state.json.
# All credentials are generated by install.sh; this file never invents defaults.

set -Eeuo pipefail

if ! declare -F load_state >/dev/null 2>&1; then
  # shellcheck source=common.sh
  source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"
fi

NEKO_SUB_DIR="${NEKO_SUB_DIR:-${NEKO_ETC}/subscriptions}"
NEKO_CONFIG_DIR="${NEKO_CONFIG_DIR:-${NEKO_ETC}/config}"

write_atomic() {
  local target="$1" mode="${2:-0640}" tmp
  mkdir -p "$(dirname -- "$target")"
  tmp="$(mktemp "${target}.tmp.XXXXXX")"
  cat > "$tmp"
  chmod "$mode" "$tmp"
  chown "root:${NEKO_USER}" "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$target"
}

render_sing_box() {
  jq -n \
    --arg domain "$DOMAIN" \
    --arg listen "$LISTEN_ADDRESS" \
    --arg cert "$CERT_FILE" \
    --arg key "$KEY_FILE" \
    --argjson tuic_port "$TUIC_PORT" \
    --arg tuic_uuid "$TUIC_UUID" \
    --arg tuic_password "$TUIC_PASSWORD" \
    --argjson ss_port "$SS_PORT" \
    --arg ss_password "$SS_PASSWORD" \
    --argjson anytls_port "$ANYTLS_PORT" \
    --arg anytls_password "$ANYTLS_PASSWORD" \
    '{
      log: {level: "info", timestamp: true},
      inbounds: [
        {
          type: "tuic",
          tag: "tuic-in",
          listen: $listen,
          listen_port: $tuic_port,
          users: [{uuid: $tuic_uuid, password: $tuic_password}],
          congestion_control: "bbr",
          zero_rtt_handshake: false,
          tls: {
            enabled: true,
            server_name: $domain,
            alpn: ["h3"],
            certificate_path: $cert,
            key_path: $key
          }
        },
        {
          type: "shadowsocks",
          tag: "ss2022-in",
          listen: $listen,
          listen_port: $ss_port,
          method: "2022-blake3-aes-128-gcm",
          password: $ss_password
        },
        {
          type: "anytls",
          tag: "anytls-in",
          listen: $listen,
          listen_port: $anytls_port,
          users: [{password: $anytls_password}],
          tls: {
            enabled: true,
            server_name: $domain,
            alpn: ["h2", "http/1.1"],
            certificate_path: $cert,
            key_path: $key
          }
        }
      ],
      outbounds: [{type: "direct", tag: "direct"}],
      route: {final: "direct"}
    }' | write_atomic "${NEKO_CONFIG_DIR}/sing-box.json"
}

render_xray() {
  jq -n \
    --arg domain "$DOMAIN" \
    --arg listen "$LISTEN_ADDRESS" \
    --argjson vision_port "$VISION_PORT" \
    --arg vision_uuid "$VISION_UUID" \
    --arg vision_private "$VISION_PRIVATE_KEY" \
    --arg vision_sid "$VISION_SHORT_ID" \
    --argjson xhttp_port "$XHTTP_PORT" \
    --arg xhttp_uuid "$XHTTP_UUID" \
    --arg xhttp_private "$XHTTP_PRIVATE_KEY" \
    --arg xhttp_sid "$XHTTP_SHORT_ID" \
    --arg xhttp_path "$XHTTP_PATH" \
    '{
      log: {loglevel: "warning"},
      inbounds: [
        {
          tag: "vless-reality-vision-in",
          listen: $listen,
          port: $vision_port,
          protocol: "vless",
          settings: {
            clients: [{id: $vision_uuid, flow: "xtls-rprx-vision"}],
            decryption: "none"
          },
          streamSettings: {
            network: "raw",
            security: "reality",
            realitySettings: {
              show: false,
              target: "127.0.0.1:8443",
              xver: 0,
              serverNames: [$domain],
              privateKey: $vision_private,
              shortIds: [$vision_sid]
            }
          },
          sniffing: {enabled: true, destOverride: ["http", "tls", "quic"]}
        },
        {
          tag: "vless-reality-xhttp-in",
          listen: $listen,
          port: $xhttp_port,
          protocol: "vless",
          settings: {
            clients: [{id: $xhttp_uuid}],
            decryption: "none"
          },
          streamSettings: {
            network: "xhttp",
            security: "reality",
            realitySettings: {
              show: false,
              target: "127.0.0.1:8443",
              xver: 0,
              serverNames: [$domain],
              privateKey: $xhttp_private,
              shortIds: [$xhttp_sid]
            },
            xhttpSettings: {
              path: $xhttp_path,
              mode: "auto"
            }
          },
          sniffing: {enabled: true, destOverride: ["http", "tls", "quic"]}
        }
      ],
      outbounds: [{protocol: "freedom", tag: "direct"}]
    }' | write_atomic "${NEKO_CONFIG_DIR}/xray.json"
}

render_hysteria() {
  write_atomic "${NEKO_CONFIG_DIR}/hysteria.yaml" <<EOF
listen: :${HY2_START}-${HY2_END}

tls:
  cert: ${CERT_FILE}
  key: ${KEY_FILE}

auth:
  type: password
  password: "${HY2_PASSWORD}"

obfs:
  type: salamander
  salamander:
    password: "${HY2_OBFS_PASSWORD}"

masquerade:
  type: proxy
  proxy:
    url: https://${DOMAIN}/
    rewriteHost: true
EOF
}

render_caddy() {
  write_atomic "${NEKO_CONFIG_DIR}/Caddyfile" <<EOF
{
	admin off
	auto_https off
	persist_config off
}

http://${DOMAIN} {
	@acme path /.well-known/acme-challenge/*
	handle @acme {
		root * ${NEKO_VAR}/acme
		file_server
	}
	handle {
		redir https://${DOMAIN}{uri} 308
	}
}

https://${DOMAIN} {
	tls ${CERT_FILE} ${KEY_FILE}
	header {
		Cache-Control "no-store"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
	}

	handle /${SUB_TOKEN}/mihomo.yaml {
		rewrite * /mihomo.yaml
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle /${SUB_TOKEN}/stash.yaml {
		rewrite * /stash.yaml
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle /${SUB_TOKEN}/shadowrocket.txt {
		rewrite * /shadowrocket.txt
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/plain; charset=utf-8"
		file_server
	}
	handle / {
		respond "Welcome" 200
	}
	handle {
		respond "Not Found" 404
	}
}

https://${DOMAIN}:8443 {
	bind 127.0.0.1
	tls ${CERT_FILE} ${KEY_FILE}
	header {
		Cache-Control "no-store"
		X-Content-Type-Options "nosniff"
	}
	respond "Welcome" 200
}
EOF
}

render_proxy_nodes() {
  cat <<EOF
  - name: "HY2"
    type: hysteria2
    server: "${DOMAIN}"
    port: ${HY2_START}
    ports: "${HY2_START}-${HY2_END}"
    hop-interval: 30
    password: "${HY2_PASSWORD}"
    obfs: salamander
    obfs-password: "${HY2_OBFS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "TUIC-v5"
    type: tuic
    server: "${DOMAIN}"
    port: ${TUIC_PORT}
    uuid: "${TUIC_UUID}"
    password: "${TUIC_PASSWORD}"
    alpn: [h3]
    disable-sni: false
    reduce-rtt: false
    udp-relay-mode: native
    congestion-controller: bbr
    skip-cert-verify: false
  - name: "SS2022"
    type: ss
    server: "${DOMAIN}"
    port: ${SS_PORT}
    cipher: "2022-blake3-aes-128-gcm"
    password: "${SS_PASSWORD}"
    udp: true
  - name: "AnyTLS"
    type: anytls
    server: "${DOMAIN}"
    port: ${ANYTLS_PORT}
    password: "${ANYTLS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h2, http/1.1]
    client-fingerprint: chrome
    udp: true
    skip-cert-verify: false
  - name: "VLESS-Reality-Vision"
    type: vless
    server: "${DOMAIN}"
    port: ${VISION_PORT}
    uuid: "${VISION_UUID}"
    encryption: ""
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${VISION_PUBLIC_KEY}"
      short-id: "${VISION_SHORT_ID}"
    skip-cert-verify: false
EOF
}

render_xhttp_node() {
  cat <<EOF
  - name: "VLESS-Reality-XHTTP"
    type: vless
    server: "${DOMAIN}"
    port: ${XHTTP_PORT}
    uuid: "${XHTTP_UUID}"
    encryption: ""
    network: xhttp
    tls: true
    udp: true
    alpn: [h2]
    servername: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${XHTTP_PUBLIC_KEY}"
      short-id: "${XHTTP_SHORT_ID}"
    xhttp-opts:
      path: "${XHTTP_PATH}"
      host: "${DOMAIN}"
      mode: stream-one
    skip-cert-verify: false
EOF
}

render_stash_yaml() {
  write_atomic "${NEKO_SUB_DIR}/stash.yaml" <<EOF
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

proxies:
  - name: "HY2"
    type: hysteria2
    server: "${DOMAIN}"
    port: ${HY2_START}
    ports: "${HY2_START}-${HY2_END}"
    hop-interval: 30
    auth: "${HY2_PASSWORD}"
    obfs: salamander
    obfs-password: "${HY2_OBFS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "TUIC-v5"
    type: tuic
    version: 5
    server: "${DOMAIN}"
    port: ${TUIC_PORT}
    uuid: "${TUIC_UUID}"
    password: "${TUIC_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "SS2022"
    type: ss
    server: "${DOMAIN}"
    port: ${SS_PORT}
    cipher: "2022-blake3-aes-128-gcm"
    password: "${SS_PASSWORD}"
    udp: true
  - name: "AnyTLS"
    type: anytls
    server: "${DOMAIN}"
    port: ${ANYTLS_PORT}
    password: "${ANYTLS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h2, http/1.1]
    skip-cert-verify: false
  - name: "VLESS-Reality-Vision"
    type: vless
    server: "${DOMAIN}"
    port: ${VISION_PORT}
    uuid: "${VISION_UUID}"
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    sni: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${VISION_PUBLIC_KEY}"
      short-id: "${VISION_SHORT_ID}"
    skip-cert-verify: false

proxy-groups:
  - name: "PROXY"
    type: select
    proxies: [HY2, TUIC-v5, SS2022, AnyTLS, VLESS-Reality-Vision]

rules:
  - MATCH,PROXY
EOF
}

render_client_yaml() {
  local target="$1" include_xhttp="$2" names
  if [[ "$include_xhttp" == "yes" ]]; then
    names='[HY2, TUIC-v5, SS2022, AnyTLS, VLESS-Reality-Vision, VLESS-Reality-XHTTP]'
  else
    names='[HY2, TUIC-v5, SS2022, AnyTLS, VLESS-Reality-Vision]'
  fi

  {
    cat <<EOF
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

proxies:
EOF
    render_proxy_nodes
    [[ "$include_xhttp" == "yes" ]] && render_xhttp_node
    cat <<EOF

proxy-groups:
  - name: "PROXY"
    type: select
    proxies: ${names}

rules:
  - MATCH,PROXY
EOF
  } | write_atomic "$target"
}

base64url_no_pad() {
  base64 -w 0 | tr '+/' '-_' | tr -d '='
}

uri_fragment() {
  local value="$1"
  value="${value//%/%25}"
  value="${value//#/%23}"
  value="${value// /%20}"
  printf '%s' "$value"
}

render_shadowrocket() {
  local ss_userinfo xhttp_path_encoded raw
  ss_userinfo="$(printf '%s' "2022-blake3-aes-128-gcm:${SS_PASSWORD}" | base64url_no_pad)"
  xhttp_path_encoded="$(urlencode_path "$XHTTP_PATH")"

  raw="$(mktemp "${NEKO_SUB_DIR}/shadowrocket.raw.XXXXXX")"
  cat > "$raw" <<EOF
hysteria2://${HY2_PASSWORD}@${DOMAIN}:${HY2_START}-${HY2_END}/?sni=${DOMAIN}&obfs=salamander&obfs-password=${HY2_OBFS_PASSWORD}&insecure=0#$(uri_fragment 'HY2')
tuic://${TUIC_UUID}:${TUIC_PASSWORD}@${DOMAIN}:${TUIC_PORT}?congestion_control=bbr&alpn=h3&sni=${DOMAIN}&udp_relay_mode=native#$(uri_fragment 'TUIC-v5')
ss://${ss_userinfo}@${DOMAIN}:${SS_PORT}#$(uri_fragment 'SS2022')
anytls://${ANYTLS_PASSWORD}@${DOMAIN}:${ANYTLS_PORT}/?sni=${DOMAIN}&insecure=0#$(uri_fragment 'AnyTLS')
vless://${VISION_UUID}@${DOMAIN}:${VISION_PORT}?encryption=none&flow=xtls-rprx-vision&security=reality&sni=${DOMAIN}&fp=chrome&pbk=${VISION_PUBLIC_KEY}&sid=${VISION_SHORT_ID}&type=tcp#$(uri_fragment 'VLESS-Reality-Vision')
vless://${XHTTP_UUID}@${DOMAIN}:${XHTTP_PORT}?encryption=none&security=reality&sni=${DOMAIN}&fp=chrome&pbk=${XHTTP_PUBLIC_KEY}&sid=${XHTTP_SHORT_ID}&type=xhttp&path=${xhttp_path_encoded}&host=${DOMAIN}&mode=stream-one#$(uri_fragment 'VLESS-Reality-XHTTP')
EOF
  { base64 -w 0 < "$raw"; printf '\n'; } | write_atomic "${NEKO_SUB_DIR}/shadowrocket.txt"
  rm -f "$raw"
}

render_subscriptions() {
  mkdir -p "$NEKO_SUB_DIR"
  render_client_yaml "${NEKO_SUB_DIR}/mihomo.yaml" yes
  # Stash does not implement XHTTP; its subscription intentionally has five nodes.
  render_stash_yaml
  render_shadowrocket
}

render_all() {
  load_state
  mkdir -p "$NEKO_CONFIG_DIR" "$NEKO_SUB_DIR"
  render_sing_box
  render_xray
  render_hysteria
  render_subscriptions
  render_caddy
}
