#!/usr/bin/env bash

# Render server configs and the three client subscriptions from state.json.
# All credentials are generated by install.sh; this file never invents defaults.

set -Eeuo pipefail

if ! declare -F load_state >/dev/null 2>&1; then
  # shellcheck source=common.sh
  source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"
fi

NEKO_SUB_DIR="${NEKO_SUB_DIR:-${NEKO_ETC}/subscriptions}"
NEKO_CONFIG_DIR="${NEKO_CONFIG_DIR:-${NEKO_ETC}/config}"

write_atomic() {
  local target="$1" mode="${2:-0640}" tmp
  mkdir -p "$(dirname -- "$target")"
  tmp="$(mktemp "${target}.tmp.XXXXXX")"
  cat > "$tmp"
  chmod "$mode" "$tmp"
  chown "root:${NEKO_USER}" "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$target"
}

render_sing_box() {
  jq -n \
    --arg domain "$DOMAIN" \
    --arg listen_v4 "$SUBSCRIPTION_IPV4_ADDRESS" \
    --arg listen_v6 "$SUBSCRIPTION_IPV6_ADDRESS" \
    --arg cert "$CERT_FILE" \
    --arg key "$KEY_FILE" \
    --argjson tuic_port "$TUIC_PORT" \
    --arg tuic_uuid "$TUIC_UUID" \
    --arg tuic_password "$TUIC_PASSWORD" \
    --argjson ss_port "$SS_PORT" \
    --arg ss_password "$SS_PASSWORD" \
    --argjson anytls_port "$ANYTLS_PORT" \
    --arg anytls_password "$ANYTLS_PASSWORD" \
    'def family_inbounds($suffix; $listen): [
        {
          type: "tuic",
          tag: ("tuic-" + $suffix + "-in"),
          listen: $listen,
          listen_port: $tuic_port,
          users: [{uuid: $tuic_uuid, password: $tuic_password}],
          congestion_control: "bbr",
          zero_rtt_handshake: false,
          tls: {
            enabled: true,
            server_name: $domain,
            alpn: ["h3"],
            certificate_path: $cert,
            key_path: $key
          }
        },
        {
          type: "shadowsocks",
          tag: ("ss2022-" + $suffix + "-in"),
          listen: $listen,
          listen_port: $ss_port,
          method: "2022-blake3-aes-128-gcm",
          password: $ss_password
        },
        {
          type: "anytls",
          tag: ("anytls-" + $suffix + "-in"),
          listen: $listen,
          listen_port: $anytls_port,
          users: [{password: $anytls_password}],
          tls: {
            enabled: true,
            server_name: $domain,
            alpn: ["h2", "http/1.1"],
            certificate_path: $cert,
            key_path: $key
          }
        }
      ];
    {
      log: {level: "info", timestamp: true},
      dns: {
        servers: [{type: "local", tag: "local"}]
      },
      inbounds: (family_inbounds("v4"; $listen_v4) + family_inbounds("v6"; $listen_v6)),
      outbounds: [
        {
          type: "direct",
          tag: "direct-v4",
          inet4_bind_address: $listen_v4,
          domain_resolver: {server: "local", strategy: "ipv4_only"}
        },
        {
          type: "direct",
          tag: "direct-v6",
          inet6_bind_address: $listen_v6,
          domain_resolver: {server: "local", strategy: "ipv6_only"}
        }
      ],
      route: {
        rules: [
          {network: "tcp", port: 25, action: "reject"},
          {
            inbound: ["tuic-v4-in", "ss2022-v4-in", "anytls-v4-in"],
            action: "resolve",
            server: "local",
            strategy: "ipv4_only"
          },
          {
            inbound: ["tuic-v6-in", "ss2022-v6-in", "anytls-v6-in"],
            action: "resolve",
            server: "local",
            strategy: "ipv6_only"
          },
          {ip_is_private: true, action: "reject"},
          {
            inbound: ["tuic-v4-in", "ss2022-v4-in", "anytls-v4-in"],
            ip_version: 6,
            action: "reject"
          },
          {
            inbound: ["tuic-v6-in", "ss2022-v6-in", "anytls-v6-in"],
            ip_version: 4,
            action: "reject"
          },
          {
            inbound: ["tuic-v4-in", "ss2022-v4-in", "anytls-v4-in"],
            action: "route",
            outbound: "direct-v4"
          },
          {
            inbound: ["tuic-v6-in", "ss2022-v6-in", "anytls-v6-in"],
            action: "route",
            outbound: "direct-v6"
          }
        ],
        final: "direct-v4"
      }
    }' | write_atomic "${NEKO_CONFIG_DIR}/sing-box.json"
}

render_xray() {
  jq -n \
    --arg domain "$DOMAIN" \
    --arg listen_v4 "$SUBSCRIPTION_IPV4_ADDRESS" \
    --arg listen_v6 "$SUBSCRIPTION_IPV6_ADDRESS" \
    --argjson vision_port "$VISION_PORT" \
    --arg vision_uuid "$VISION_UUID" \
    --arg vision_private "$VISION_PRIVATE_KEY" \
    --arg vision_sid "$VISION_SHORT_ID" \
    --argjson xhttp_port "$XHTTP_PORT" \
    --arg xhttp_uuid "$XHTTP_UUID" \
    --arg xhttp_private "$XHTTP_PRIVATE_KEY" \
    --arg xhttp_sid "$XHTTP_SHORT_ID" \
    --arg xhttp_path "$XHTTP_PATH" \
    'def vision_inbound($suffix; $listen): {
        tag: ("vless-reality-vision-" + $suffix + "-in"),
        listen: $listen,
        port: $vision_port,
        protocol: "vless",
        settings: {
          clients: [{id: $vision_uuid, flow: "xtls-rprx-vision"}],
          decryption: "none"
        },
        streamSettings: {
          network: "raw",
          security: "reality",
          realitySettings: {
            show: false,
            target: "127.0.0.1:8443",
            xver: 0,
            serverNames: [$domain],
            privateKey: $vision_private,
            shortIds: [$vision_sid]
          }
        },
        sniffing: {enabled: true, destOverride: ["http", "tls", "quic"]}
      };
    def xhttp_inbound($suffix; $listen): {
        tag: ("vless-reality-xhttp-" + $suffix + "-in"),
        listen: $listen,
        port: $xhttp_port,
        protocol: "vless",
        settings: {
          clients: [{id: $xhttp_uuid}],
          decryption: "none"
        },
        streamSettings: {
          network: "xhttp",
          security: "reality",
          realitySettings: {
            show: false,
            target: "127.0.0.1:8443",
            xver: 0,
            serverNames: [$domain],
            privateKey: $xhttp_private,
            shortIds: [$xhttp_sid]
          },
          xhttpSettings: {
            path: $xhttp_path,
            mode: "auto"
          }
        },
        sniffing: {enabled: true, destOverride: ["http", "tls", "quic"]}
      };
    {
      log: {loglevel: "warning"},
      inbounds: [
        vision_inbound("v4"; $listen_v4),
        vision_inbound("v6"; $listen_v6),
        xhttp_inbound("v4"; $listen_v4),
        xhttp_inbound("v6"; $listen_v6)
      ],
      outbounds: [
        {
          sendThrough: $listen_v4,
          protocol: "freedom",
          tag: "direct-v4",
          targetStrategy: "ForceIPv4",
          settings: {domainStrategy: "ForceIPv4"}
        },
        {
          sendThrough: $listen_v6,
          protocol: "freedom",
          tag: "direct-v6",
          targetStrategy: "ForceIPv6",
          settings: {domainStrategy: "ForceIPv6"}
        },
        {protocol: "blackhole", tag: "blocked"}
      ],
      routing: {
        domainStrategy: "IPIfNonMatch",
        rules: [
          {
            type: "field",
            ip: [
              "0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10",
              "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12",
              "192.0.0.0/24", "192.168.0.0/16", "198.18.0.0/15",
              "224.0.0.0/4", "240.0.0.0/4",
              "::/128", "::1/128", "fc00::/7", "fe80::/10", "ff00::/8"
            ],
            outboundTag: "blocked"
          },
          {
            type: "field",
            network: "tcp",
            port: 25,
            outboundTag: "blocked"
          },
          {
            type: "field",
            inboundTag: ["vless-reality-vision-v4-in", "vless-reality-xhttp-v4-in"],
            outboundTag: "direct-v4"
          },
          {
            type: "field",
            inboundTag: ["vless-reality-vision-v6-in", "vless-reality-xhttp-v6-in"],
            outboundTag: "direct-v6"
          }
        ]
      }
    }' | write_atomic "${NEKO_CONFIG_DIR}/xray.json"
}

render_hysteria_family() {
  local target="$1" listen="$2" mode="$3" bind_field="$4" bind_address="$5"
  write_atomic "$target" <<EOF
listen: "${listen}"

tls:
  cert: ${CERT_FILE}
  key: ${KEY_FILE}

auth:
  type: password
  password: "${HY2_PASSWORD}"

obfs:
  type: salamander
  salamander:
    password: "${HY2_OBFS_PASSWORD}"

masquerade:
  type: proxy
  proxy:
    url: https://${DOMAIN}/
    rewriteHost: true

outbounds:
  - name: direct
    type: direct
    direct:
      mode: ${mode}
      ${bind_field}: ${bind_address}

acl:
  inline:
    - reject(0.0.0.0/8)
    - reject(10.0.0.0/8)
    - reject(100.64.0.0/10)
    - reject(127.0.0.0/8)
    - reject(169.254.0.0/16)
    - reject(172.16.0.0/12)
    - reject(192.0.0.0/24)
    - reject(192.168.0.0/16)
    - reject(198.18.0.0/15)
    - reject(224.0.0.0/4)
    - reject(240.0.0.0/4)
    - reject(::/128)
    - reject(::1/128)
    - reject(fc00::/7)
    - reject(fe80::/10)
    - reject(ff00::/8)
    - reject(all, tcp/25)
    - direct(all)
EOF
}

render_hysteria() {
  render_hysteria_family \
    "${NEKO_CONFIG_DIR}/hysteria-v4.yaml" \
    "${SUBSCRIPTION_IPV4_ADDRESS}:${HY2_START}-${HY2_END}" \
    4 bindIPv4 "$SUBSCRIPTION_IPV4_ADDRESS"
  render_hysteria_family \
    "${NEKO_CONFIG_DIR}/hysteria-v6.yaml" \
    "[${SUBSCRIPTION_IPV6_ADDRESS}]:${HY2_START}-${HY2_END}" \
    6 bindIPv6 "$SUBSCRIPTION_IPV6_ADDRESS"
  rm -f -- "${NEKO_CONFIG_DIR}/hysteria.yaml"
}

render_caddy() {
  write_atomic "${NEKO_CONFIG_DIR}/Caddyfile" <<EOF
{
	admin off
	auto_https off
	persist_config off
	servers {
		protocols h1 h2
	}
}

http://${DOMAIN}, http://${SUBSCRIPTION_DOMAIN_IPV4}, http://${SUBSCRIPTION_DOMAIN_IPV6} {
	@acme path /.well-known/acme-challenge/*
	handle @acme {
		root * ${NEKO_VAR}/acme
		file_server
	}
	handle {
		redir https://{host}{uri} 308
	}
}

https://${DOMAIN} {
	tls ${CERT_FILE} ${KEY_FILE}
	header {
		Cache-Control "no-store"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
	}
	handle {
		respond "Welcome" 200
	}
}

https://${SUBSCRIPTION_DOMAIN_IPV4} {
	tls ${CERT_FILE} ${KEY_FILE}
	header {
		Cache-Control "no-store"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
	}

	handle /${SUB_TOKEN}/mihomo.yaml {
		rewrite * /mihomo-v4.yaml
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle /${SUB_TOKEN}/stash.yaml {
		rewrite * /stash-v4.yaml
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle /${SUB_TOKEN}/shadowrocket.txt {
		rewrite * /shadowrocket-v4.txt
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle {
		respond "Not Found" 404
	}
}

https://${SUBSCRIPTION_DOMAIN_IPV6} {
	tls ${CERT_FILE} ${KEY_FILE}
	header {
		Cache-Control "no-store"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "no-referrer"
	}

	handle /${SUB_TOKEN}/mihomo.yaml {
		rewrite * /mihomo-v6.yaml
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle /${SUB_TOKEN}/stash.yaml {
		rewrite * /stash-v6.yaml
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle /${SUB_TOKEN}/shadowrocket.txt {
		rewrite * /shadowrocket-v6.txt
		root * ${NEKO_SUB_DIR}
		header Content-Type "text/yaml; charset=utf-8"
		file_server
	}
	handle {
		respond "Not Found" 404
	}
}

https://${DOMAIN}:8443 {
	bind 127.0.0.1
	tls ${CERT_FILE} ${KEY_FILE}
	header {
		Cache-Control "no-store"
		X-Content-Type-Options "nosniff"
	}
	respond "Welcome" 200
}
EOF
}

render_proxy_nodes() {
  local server="$1" ip_version="$2"
  cat <<EOF
  - name: "HY2"
    type: hysteria2
    server: "${server}"
    ip-version: ${ip_version}
    port: ${HY2_START}
    ports: "${HY2_START}-${HY2_END}"
    hop-interval: 30
    password: "${HY2_PASSWORD}"
    obfs: salamander
    obfs-password: "${HY2_OBFS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "TUIC-v5"
    type: tuic
    server: "${server}"
    ip-version: ${ip_version}
    port: ${TUIC_PORT}
    uuid: "${TUIC_UUID}"
    password: "${TUIC_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    disable-sni: false
    reduce-rtt: false
    udp-relay-mode: native
    congestion-controller: bbr
    skip-cert-verify: false
  - name: "SS2022"
    type: ss
    server: "${server}"
    ip-version: ${ip_version}
    port: ${SS_PORT}
    cipher: "2022-blake3-aes-128-gcm"
    password: "${SS_PASSWORD}"
    udp: true
  - name: "AnyTLS"
    type: anytls
    server: "${server}"
    ip-version: ${ip_version}
    port: ${ANYTLS_PORT}
    password: "${ANYTLS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h2, http/1.1]
    client-fingerprint: chrome
    udp: true
    skip-cert-verify: false
  - name: "VLESS-Reality-Vision"
    type: vless
    server: "${server}"
    ip-version: ${ip_version}
    port: ${VISION_PORT}
    uuid: "${VISION_UUID}"
    encryption: ""
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${VISION_PUBLIC_KEY}"
      short-id: "${VISION_SHORT_ID}"
    skip-cert-verify: false
EOF
}

render_xhttp_node() {
  local server="$1" ip_version="$2"
  cat <<EOF
  - name: "VLESS-Reality-XHTTP"
    type: vless
    server: "${server}"
    ip-version: ${ip_version}
    port: ${XHTTP_PORT}
    uuid: "${XHTTP_UUID}"
    encryption: ""
    network: xhttp
    tls: true
    udp: true
    alpn: [h2]
    servername: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${XHTTP_PUBLIC_KEY}"
      short-id: "${XHTTP_SHORT_ID}"
    xhttp-opts:
      path: "${XHTTP_PATH}"
      host: "${DOMAIN}"
      mode: stream-one
    skip-cert-verify: false
EOF
}

render_stash_yaml() {
  local target="$1" server="$2"
  write_atomic "$target" <<EOF
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

proxies:
  - name: "HY2"
    type: hysteria2
    server: "${server}"
    port: ${HY2_START}
    ports: "${HY2_START}-${HY2_END}"
    hop-interval: 30
    auth: "${HY2_PASSWORD}"
    obfs: salamander
    obfs-password: "${HY2_OBFS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "TUIC-v5"
    type: tuic
    version: 5
    server: "${server}"
    port: ${TUIC_PORT}
    uuid: "${TUIC_UUID}"
    password: "${TUIC_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "SS2022"
    type: ss
    server: "${server}"
    port: ${SS_PORT}
    cipher: "2022-blake3-aes-128-gcm"
    password: "${SS_PASSWORD}"
    udp: true
  - name: "AnyTLS"
    type: anytls
    server: "${server}"
    port: ${ANYTLS_PORT}
    password: "${ANYTLS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h2, http/1.1]
    skip-cert-verify: false
  - name: "VLESS-Reality-Vision"
    type: vless
    server: "${server}"
    port: ${VISION_PORT}
    uuid: "${VISION_UUID}"
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    sni: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${VISION_PUBLIC_KEY}"
      short-id: "${VISION_SHORT_ID}"
    skip-cert-verify: false

proxy-groups:
  - name: "PROXY"
    type: select
    proxies: [HY2, TUIC-v5, SS2022, AnyTLS, VLESS-Reality-Vision]

rules:
  - MATCH,PROXY
EOF
}

render_client_yaml() {
  local target="$1" include_xhttp="$2" server="$3" ip_version="$4" names
  if [[ "$include_xhttp" == "yes" ]]; then
    names='[HY2, TUIC-v5, SS2022, AnyTLS, VLESS-Reality-Vision, VLESS-Reality-XHTTP]'
  else
    names='[HY2, TUIC-v5, SS2022, AnyTLS, VLESS-Reality-Vision]'
  fi

  {
    cat <<EOF
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true

proxies:
EOF
    render_proxy_nodes "$server" "$ip_version"
    [[ "$include_xhttp" == "yes" ]] && render_xhttp_node "$server" "$ip_version"
    cat <<EOF

proxy-groups:
  - name: "PROXY"
    type: select
    proxies: ${names}

rules:
  - MATCH,PROXY
EOF
  } | write_atomic "$target"
}

render_shadowrocket() {
  local target="$1" server="$2"
  # The strict variants use an IP literal so Shadowrocket cannot resolve or
  # fall back to the other address family. TLS SNI, REALITY serverName and
  # XHTTP Host remain bound to the certificate domain.
  write_atomic "$target" <<EOF
proxies:
  - name: "HY2"
    type: hysteria2
    server: "${server}"
    port: ${HY2_START}
    ports: "${HY2_START}-${HY2_END}"
    port-range: "${HY2_START}-${HY2_END}"
    hop-interval: 30
    password: "${HY2_PASSWORD}"
    obfs: salamander
    obfs-password: "${HY2_OBFS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    skip-cert-verify: false
  - name: "TUIC-v5"
    type: tuic
    version: 5
    server: "${server}"
    port: ${TUIC_PORT}
    uuid: "${TUIC_UUID}"
    password: "${TUIC_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h3]
    udp-relay-mode: native
    congestion-controller: bbr
    skip-cert-verify: false
  - name: "SS2022"
    type: ss
    server: "${server}"
    port: ${SS_PORT}
    cipher: "2022-blake3-aes-128-gcm"
    password: "${SS_PASSWORD}"
    udp: true
  - name: "AnyTLS"
    type: anytls
    server: "${server}"
    port: ${ANYTLS_PORT}
    password: "${ANYTLS_PASSWORD}"
    sni: "${DOMAIN}"
    alpn: [h2, http/1.1]
    client-fingerprint: chrome
    skip-cert-verify: false
  - name: "VLESS-Reality-Vision"
    type: vless
    server: "${server}"
    port: ${VISION_PORT}
    uuid: "${VISION_UUID}"
    encryption: ""
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${VISION_PUBLIC_KEY}"
      short-id: "${VISION_SHORT_ID}"
    skip-cert-verify: false
  - name: "VLESS-Reality-XHTTP"
    type: vless
    server: "${server}"
    port: ${XHTTP_PORT}
    uuid: "${XHTTP_UUID}"
    encryption: ""
    network: xhttp
    tls: true
    udp: true
    alpn: [h2]
    servername: "${DOMAIN}"
    client-fingerprint: chrome
    reality-opts:
      public-key: "${XHTTP_PUBLIC_KEY}"
      short-id: "${XHTTP_SHORT_ID}"
    xhttp-opts:
      path: "${XHTTP_PATH}"
      host: "${DOMAIN}"
      mode: stream-one
    skip-cert-verify: false
EOF
}

render_subscriptions() {
  mkdir -p "$NEKO_SUB_DIR"
  render_client_yaml "${NEKO_SUB_DIR}/mihomo-v4.yaml" yes \
    "$SUBSCRIPTION_IPV4_ADDRESS" ipv4
  render_client_yaml "${NEKO_SUB_DIR}/mihomo-v6.yaml" yes \
    "$SUBSCRIPTION_IPV6_ADDRESS" ipv6
  # Stash does not implement XHTTP; each strict subscription has five nodes.
  render_stash_yaml "${NEKO_SUB_DIR}/stash-v4.yaml" "$SUBSCRIPTION_IPV4_ADDRESS"
  render_stash_yaml "${NEKO_SUB_DIR}/stash-v6.yaml" "$SUBSCRIPTION_IPV6_ADDRESS"
  render_shadowrocket "${NEKO_SUB_DIR}/shadowrocket-v4.txt" "$SUBSCRIPTION_IPV4_ADDRESS"
  render_shadowrocket "${NEKO_SUB_DIR}/shadowrocket-v6.txt" "$SUBSCRIPTION_IPV6_ADDRESS"
}

render_all() {
  load_state
  mkdir -p "$NEKO_CONFIG_DIR" "$NEKO_SUB_DIR"
  render_sing_box
  render_xray
  render_hysteria
  render_subscriptions
  render_caddy
}
